export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      site_settings: {
        Row: {
          id: string;
          site_name: string;
          short_description: string | null;
          logo_url: string | null;
          favicon_url: string | null;
          primary_color: string | null;
          secondary_color: string | null;
          accent_color: string | null;
          whatsapp: string | null;
          email: string | null;
          phone: string | null;
          address: string | null;
          instagram_url: string | null;
          facebook_url: string | null;
          linkedin_url: string | null;
          opening_hours: string | null;
          institutional_image_url: string | null;
          footer_newsletter_title: string | null;
          footer_newsletter_text: string | null;
          footer_newsletter_button_label: string | null;
          footer_copyright_text: string | null;
          footer_institutional_phrase: string | null;
          youtube_url: string | null;
          footer_legal_text: string | null;
          copyright_text: string | null;
          copyright_year: string | null;
          default_whatsapp_message: string | null;
          leasing_whatsapp_message: string | null;
          planning_whatsapp_message: string | null;
          hotel_whatsapp_message: string | null;
          business_center_whatsapp_message: string | null;
          login_title: string | null;
          login_subtitle: string | null;
          login_image_url: string | null;
          default_og_image_url: string | null;
          google_analytics_id: string | null;
          google_tag_manager_id: string | null;
          meta_pixel_id: string | null;
          custom_head_scripts: string | null;
          custom_body_scripts: string | null;
          seo_base_url: string | null;
          seo_default_robots: string | null;
          seo_default_language: string | null;
          seo_keywords: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_name: string;
          short_description?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          accent_color?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          instagram_url?: string | null;
          facebook_url?: string | null;
          linkedin_url?: string | null;
          opening_hours?: string | null;
          institutional_image_url?: string | null;
          footer_newsletter_title?: string | null;
          footer_newsletter_text?: string | null;
          footer_newsletter_button_label?: string | null;
          footer_copyright_text?: string | null;
          footer_institutional_phrase?: string | null;
          youtube_url?: string | null;
          footer_legal_text?: string | null;
          copyright_text?: string | null;
          copyright_year?: string | null;
          default_whatsapp_message?: string | null;
          leasing_whatsapp_message?: string | null;
          planning_whatsapp_message?: string | null;
          hotel_whatsapp_message?: string | null;
          business_center_whatsapp_message?: string | null;
          login_title?: string | null;
          login_subtitle?: string | null;
          login_image_url?: string | null;
          default_og_image_url?: string | null;
          google_analytics_id?: string | null;
          google_tag_manager_id?: string | null;
          meta_pixel_id?: string | null;
          custom_head_scripts?: string | null;
          custom_body_scripts?: string | null;
          seo_base_url?: string | null;
          seo_default_robots?: string | null;
          seo_default_language?: string | null;
          seo_keywords?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          site_name?: string;
          short_description?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          accent_color?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          instagram_url?: string | null;
          facebook_url?: string | null;
          linkedin_url?: string | null;
          opening_hours?: string | null;
          institutional_image_url?: string | null;
          footer_newsletter_title?: string | null;
          footer_newsletter_text?: string | null;
          footer_newsletter_button_label?: string | null;
          footer_copyright_text?: string | null;
          footer_institutional_phrase?: string | null;
          youtube_url?: string | null;
          footer_legal_text?: string | null;
          copyright_text?: string | null;
          copyright_year?: string | null;
          default_whatsapp_message?: string | null;
          leasing_whatsapp_message?: string | null;
          planning_whatsapp_message?: string | null;
          hotel_whatsapp_message?: string | null;
          business_center_whatsapp_message?: string | null;
          login_title?: string | null;
          login_subtitle?: string | null;
          login_image_url?: string | null;
          default_og_image_url?: string | null;
          google_analytics_id?: string | null;
          google_tag_manager_id?: string | null;
          meta_pixel_id?: string | null;
          custom_head_scripts?: string | null;
          custom_body_scripts?: string | null;
          seo_base_url?: string | null;
          seo_default_robots?: string | null;
          seo_default_language?: string | null;
          seo_keywords?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      pages: {
        Row: {
          id: string;
          slug: string;
          title: string;
          subtitle: string | null;
          content: string | null;
          hero_image_url: string | null;
          seo_title: string | null;
          seo_description: string | null;
          og_image_url: string | null;
          og_title: string | null;
          og_description: string | null;
          canonical_url: string | null;
          robots_index: boolean;
          robots_follow: boolean;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          content?: string | null;
          hero_image_url?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          og_title?: string | null;
          og_description?: string | null;
          canonical_url?: string | null;
          robots_index?: boolean;
          robots_follow?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          content?: string | null;
          hero_image_url?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          og_title?: string | null;
          og_description?: string | null;
          canonical_url?: string | null;
          robots_index?: boolean;
          robots_follow?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      home_sections: {
        Row: {
          id: string;
          section_key: string;
          title: string | null;
          subtitle: string | null;
          content: string | null;
          image_url: string | null;
          button_label: string | null;
          button_url: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          section_key: string;
          title?: string | null;
          subtitle?: string | null;
          content?: string | null;
          image_url?: string | null;
          button_label?: string | null;
          button_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          section_key?: string;
          title?: string | null;
          subtitle?: string | null;
          content?: string | null;
          image_url?: string | null;
          button_label?: string | null;
          button_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      content_blocks: {
        Row: {
          id: string;
          page_key: string;
          block_key: string;
          block_type: string;
          title: string | null;
          subtitle: string | null;
          content: string | null;
          image_url: string | null;
          icon: string | null;
          button_label: string | null;
          button_url: string | null;
          secondary_button_label: string | null;
          secondary_button_url: string | null;
          settings: Json;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          page_key: string;
          block_key: string;
          block_type: string;
          title?: string | null;
          subtitle?: string | null;
          content?: string | null;
          image_url?: string | null;
          icon?: string | null;
          button_label?: string | null;
          button_url?: string | null;
          secondary_button_label?: string | null;
          secondary_button_url?: string | null;
          settings?: Json;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          page_key?: string;
          block_key?: string;
          block_type?: string;
          title?: string | null;
          subtitle?: string | null;
          content?: string | null;
          image_url?: string | null;
          icon?: string | null;
          button_label?: string | null;
          button_url?: string | null;
          secondary_button_label?: string | null;
          secondary_button_url?: string | null;
          settings?: Json;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      content_block_items: {
        Row: {
          id: string;
          block_id: string;
          title: string | null;
          subtitle: string | null;
          content: string | null;
          image_url: string | null;
          icon: string | null;
          button_label: string | null;
          button_url: string | null;
          metadata: Json;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          block_id: string;
          title?: string | null;
          subtitle?: string | null;
          content?: string | null;
          image_url?: string | null;
          icon?: string | null;
          button_label?: string | null;
          button_url?: string | null;
          metadata?: Json;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          block_id?: string;
          title?: string | null;
          subtitle?: string | null;
          content?: string | null;
          image_url?: string | null;
          icon?: string | null;
          button_label?: string | null;
          button_url?: string | null;
          metadata?: Json;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      navigation_items: {
        Row: {
          id: string;
          label: string;
          url: string;
          location: string;
          icon: string | null;
          style: string | null;
          sort_order: number;
          is_active: boolean;
          open_in_new_tab: boolean;
          requires_auth: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          url: string;
          location: string;
          icon?: string | null;
          style?: string | null;
          sort_order?: number;
          is_active?: boolean;
          open_in_new_tab?: boolean;
          requires_auth?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          url?: string;
          location?: string;
          icon?: string | null;
          style?: string | null;
          sort_order?: number;
          is_active?: boolean;
          open_in_new_tab?: boolean;
          requires_auth?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      footer_sections: {
        Row: {
          id: string;
          title: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      footer_links: {
        Row: {
          id: string;
          footer_section_id: string;
          label: string;
          url: string;
          sort_order: number;
          is_active: boolean;
          open_in_new_tab: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          footer_section_id: string;
          label: string;
          url: string;
          sort_order?: number;
          is_active?: boolean;
          open_in_new_tab?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          footer_section_id?: string;
          label?: string;
          url?: string;
          sort_order?: number;
          is_active?: boolean;
          open_in_new_tab?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          color: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stores: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          category_id: string | null;
          segment: string | null;
          floor: string | null;
          store_number: string | null;
          whatsapp: string | null;
          phone: string | null;
          email: string | null;
          instagram: string | null;
          website: string | null;
          logo_url: string | null;
          banner_url: string | null;
          tags: string[] | null;
          seo_title: string | null;
          seo_description: string | null;
          og_image_url: string | null;
          is_featured: boolean;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          category_id?: string | null;
          segment?: string | null;
          floor?: string | null;
          store_number?: string | null;
          whatsapp?: string | null;
          phone?: string | null;
          email?: string | null;
          instagram?: string | null;
          website?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          tags?: string[] | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          is_featured?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          category_id?: string | null;
          segment?: string | null;
          floor?: string | null;
          store_number?: string | null;
          whatsapp?: string | null;
          phone?: string | null;
          email?: string | null;
          instagram?: string | null;
          website?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          tags?: string[] | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          is_featured?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      store_products: {
        Row: {
          id: string;
          store_id: string;
          name: string;
          description: string | null;
          image_url: string | null;
          category: string | null;
          price: number | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          name: string;
          description?: string | null;
          image_url?: string | null;
          category?: string | null;
          price?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          category?: string | null;
          price?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      store_media: {
        Row: {
          id: string;
          store_id: string;
          media_url: string;
          media_type: string;
          title: string | null;
          alt_text: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          media_url: string;
          media_type: string;
          title?: string | null;
          alt_text?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          media_url?: string;
          media_type?: string;
          title?: string | null;
          alt_text?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      catalogs: {
        Row: {
          id: string;
          store_id: string;
          title: string;
          file_url: string;
          file_size: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          title: string;
          file_url: string;
          file_size?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          title?: string;
          file_url?: string;
          file_size?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      launches: {
        Row: {
          id: string;
          store_id: string | null;
          title: string;
          description: string | null;
          image_url: string | null;
          category_id: string | null;
          price: number | null;
          publish_date: string | null;
          expiration_date: string | null;
          seo_title: string | null;
          seo_description: string | null;
          og_image_url: string | null;
          is_featured: boolean;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id?: string | null;
          title: string;
          description?: string | null;
          image_url?: string | null;
          category_id?: string | null;
          price?: number | null;
          publish_date?: string | null;
          expiration_date?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          is_featured?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string | null;
          title?: string;
          description?: string | null;
          image_url?: string | null;
          category_id?: string | null;
          price?: number | null;
          publish_date?: string | null;
          expiration_date?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          is_featured?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          type: string;
          name: string;
          email: string | null;
          phone: string | null;
          company: string | null;
          cnpj: string | null;
          segment: string | null;
          message: string | null;
          source_page: string | null;
          status: string;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          cnpj?: string | null;
          segment?: string | null;
          message?: string | null;
          source_page?: string | null;
          status?: string;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          cnpj?: string | null;
          segment?: string | null;
          message?: string | null;
          source_page?: string | null;
          status?: string;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      newsletter_subscribers: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          status: string;
          consent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name?: string | null;
          status?: string;
          consent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          status?: string;
          consent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_profiles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          role: string;
          avatar_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          role?: string;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          role?: string;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      activity_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity: string;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity?: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_super_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

export type TableName = keyof Database['public']['Tables'];

export type TableRow<T extends TableName> = Database['public']['Tables'][T]['Row'];
export type TableInsert<T extends TableName> = Database['public']['Tables'][T]['Insert'];
export type TableUpdate<T extends TableName> = Database['public']['Tables'][T]['Update'];
