export const FALLBACK_SITE_SETTINGS = {
  site_name: 'Shopping Mega Polo Moda',
  short_description: 'Selecao de lojas, lancamentos e oportunidades de moda atacadista.',
  logo_url: '/images/logo-mega-polo.png',
  favicon_url: '/favicon.ico',
  primary_color: '#E30613',
  secondary_color: '#1A1A1A',
  accent_color: '#D4AF37',
  whatsapp: '551133112887',
  email: 'contato@megapolomoda.com.br',
  phone: '(11) 3311-2800',
  address: 'Rua Barao de Ladario, 670 - Bras, Sao Paulo - SP',
  instagram_url: 'https://www.instagram.com/megapolomoda',
  facebook_url: 'https://www.facebook.com/megapolomoda',
  linkedin_url: '',
  opening_hours: 'Segunda a sabado, das 6h as 18h',
  institutional_image_url: '',
  footer_newsletter_title: 'Insights',
  footer_newsletter_text: 'Receba os destaques do Bras em seu e-mail.',
  footer_newsletter_button_label: 'Cadastrar',
  footer_copyright_text: 'Shopping Mega Polo Moda',
  footer_institutional_phrase: 'Referencia em moda atacadista no Bras.',
  youtube_url: 'https://www.youtube.com/@megapolomoda',
  footer_legal_text: 'Informacoes sujeitas a alteracao sem aviso previo.',
  copyright_text: 'Mega Polo Moda',
  copyright_year: new Date().getFullYear().toString(),
  default_whatsapp_message: 'Ola, gostaria de mais informacoes sobre o Mega Polo Moda.',
  leasing_whatsapp_message:
    'Ola, tenho interesse em abrir uma loja no Mega Polo Moda e gostaria de mais informacoes.',
  planning_whatsapp_message:
    'Ola, gostaria de mais informacoes sobre o planejamento de visita ao Mega Polo Moda.',
  hotel_whatsapp_message: 'Ola, gostaria de informacoes sobre hospedagem no Hotel Mega Polo.',
  business_center_whatsapp_message:
    'Ola, gostaria de informacoes sobre o Centro Empresarial do Mega Polo Moda.',
  login_title: 'Area do Lojista',
  login_subtitle: 'Acesse para gerenciar sua loja, lancamentos e informacoes comerciais.',
  login_image_url: '/images/logo-mega-polo.png',
  default_og_image_url: '/images/logo-mega-polo.png',
  google_analytics_id: '',
  google_tag_manager_id: '',
  meta_pixel_id: '',
  custom_head_scripts: '',
  custom_body_scripts: '',
  seo_base_url: '',
  seo_default_robots: 'index,follow',
  seo_default_language: 'pt-BR',
  seo_keywords: '',
} as const;

export const SITE_SETTINGS_STORAGE_BUCKET = 'logos';
export const SITE_SETTINGS_INSTITUTIONAL_BUCKET = 'institutional';
